# Generated by Django 4.2.10 on 2024-02-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0003_alter_userprofile_profilepicurl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
