# Generated by Django 4.2.10 on 2024-02-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0004_userprofile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mediaCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followersCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followsCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
