# Generated by Django 4.2.10 on 2024-02-18 01:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0005_userprofile_mediacount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='media',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
