# Generated by Django 4.2.10 on 2024-02-18 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0006_userprofile_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='media',
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('thumbnail_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('userProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pythonApi.userprofile')),
            ],
        ),
    ]
