# Generated by Django 4.2.10 on 2024-02-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0007_remove_userprofile_media_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('requestTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
