# Generated by Django 4.2.10 on 2024-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0008_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='followersCount',
            new_name='followers_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='followsCount',
            new_name='follows_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='mediaCount',
            new_name='media_count',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profilePicUrl',
            new_name='profile_pic_url',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
