# Generated by Django 4.2.10 on 2024-02-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0010_rename_requesttime_request_request_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
