# Generated by Django 4.2.10 on 2024-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonApi', '0012_media_comments_media_date_media_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
